# Uncomment these two line to add support for encoders to your firmware
#CONFIG_EC11=y
#CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the KLOR OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable per key RGB
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Backlight
# CONFIG_ZMK_BACKLIGHT=y

#CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=40


# Force USB output by default
CONFIG_ZMK_USB_BOOT=y


# Disable bluetooth advertisement
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_DEVICE_NAME="A4ECB4481FC2"

# For a standard split, 1 connection is used for the split peripheral.
# Setting this to 1 usually prevents the "Central" from advertising to a phone.
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1

# 3. Disable advertising for new hosts
CONFIG_ZMK_BLE_PASSIVE_PERIPHERAL_BOUND=y
